/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Hitbox;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelos.Empleado;

/**
 *
 * @author Michelle
 */
public class Empleados extends javax.swing.JFrame {
    DefaultTableModel tabla;
    Hitbox contol = new Hitbox ();
    String operacion = "", id = "-1";
    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        setLocationRelativeTo(null);
        iniciaBotones();
        cargaTabla();
    }

    public void iniciaBotones() {
        Guardar.setEnabled(false);
        Cancelar.setEnabled(false);
        Borrar.setEnabled(false);
        Nuevo.setEnabled(true);
        idSucTxt.setEnabled(false);
        nombreTxt.setEnabled(false);
        direccionTxt.setEnabled(false);
        telTxt.setEnabled(false);
        edadTxt.setEnabled(false);
        refComTxt.setEnabled(false);
        generoTxt.setEnabled(false);
    }
   
    private void cargaTabla (){
        String [] titulos = {"Id", "Sucursal", "Nombre", "Edad", "Género", "Dirección", "Telefono", "Referencias C."};
        String [] registro = new String [8];
        Empleado empleado;
        ArrayList empleados;
        tabla = new DefaultTableModel(null,titulos);
        empleados = contol.listaEmpleados ();
        for (int i = 0; i < empleados.size(); i++)
        {
            empleado = (Empleado) empleados.get(i);
            registro [0] = Integer.toString (empleado.getId_empleado ());
            registro [1] = Integer.toString (empleado.getSuc_codigo ());
            registro [2] = empleado.getNom_empleado ();
            registro [3] = Integer.toString (empleado.getEdad ());
            registro [4] = empleado.getGenero ();
            registro [5] = empleado.getDireccion ();
            registro [6] = empleado.getTel_empleado ();
            registro [7] = empleado.getReferencias_comerciales ();
            tabla.addRow (registro);
        }
        tablaEmpleados.setModel(tabla);
        tablaEmpleados.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscaTxt = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        edadTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        direccionTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        refComTxt = new javax.swing.JTextField();
        Nuevo = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        idSucTxt = new javax.swing.JTextField();
        generoTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();

        setTitle("Control de Empleados");
        setResizable(false);

        buscaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaTxtActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        edadTxt.setText("Edad");
        edadTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edadTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edadTxtFocusLost(evt);
            }
        });
        edadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadTxtActionPerformed(evt);
            }
        });

        telTxt.setText("Telefono");
        telTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTxtActionPerformed(evt);
            }
        });
        telTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telTxtFocusLost(evt);
            }
        });

        direccionTxt.setText("Direccion");
        direccionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTxtActionPerformed(evt);
            }
        });
        direccionTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionTxtFocusLost(evt);
            }
        });

        jLabel3.setText("Genero");

        nombreTxt.setText("Nombre");
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        nombreTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTxtFocusLost(evt);
            }
        });

        jLabel4.setText("Empleado en la sucursal");

        refComTxt.setText("Referencias comerciales");
        refComTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                refComTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                refComTxtFocusLost(evt);
            }
        });

        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/icono-aniadir.gif"))); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/icono_borrar_objeto.gif"))); // NOI18N
        Borrar.setText("Borrar");
        Borrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/basic-icon-save.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/cliente.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/pastel1.gif"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/down_icon2.gif"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/map_icon.gif"))); // NOI18N

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/Nuevo_icono_restricción_prohibida.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idSucTxt))
                    .addComponent(direccionTxt)
                    .addComponent(nombreTxt)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(edadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refComTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(refComTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idSucTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cancelar))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(generoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Sucursal", "Nombre", "Edad", "Género", "Dirección", "Telefono", "Referencias C."
            }
        ));
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(buscaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaTxtActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String [] titulos = {"Id", "Sucursal", "Nombre", "Edad", "Género", "Dirección", "Telefono", "Referencias C."};
        String [] registro = new String [7];
        Empleado empleado;
        ArrayList empleados;
        tabla = new DefaultTableModel(null,titulos);
        empleados = contol.listaEmpleadoBuscados (buscaTxt.getText());
        for (int i = 0; i < empleados.size(); i++)
        {
            empleado = (Empleado) empleados.get(i);
            registro [0] = Integer.toString (empleado.getId_empleado ());
            registro [1] = Integer.toString (empleado.getSuc_codigo ());
            registro [2] = empleado.getNom_empleado ();
            registro [3] = Integer.toString (empleado.getEdad ());
            registro [4] = empleado.getGenero ();
            registro [5] = empleado.getDireccion ();
            registro [6] = empleado.getTel_empleado ();
            registro [7] = empleado.getReferencias_comerciales ();
            tabla.addRow (registro);
        }
        tablaEmpleados.setModel(tabla);
        tablaEmpleados.setEnabled(true);
    }//GEN-LAST:event_buscarActionPerformed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void direccionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTxtActionPerformed

    private void telTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtActionPerformed

    private void edadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadTxtActionPerformed

    private void nombreTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTxtFocusGained
        String tex;
        tex = nombreTxt.getText();
        if (tex.equals("Nombre")){
            nombreTxt.setText("");
        }
    }//GEN-LAST:event_nombreTxtFocusGained

    private void nombreTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTxtFocusLost
        String tex;
        tex = nombreTxt.getText();
        if (tex.equals("")){
            nombreTxt.setText("Nombre");
        }
    }//GEN-LAST:event_nombreTxtFocusLost

    private void edadTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edadTxtFocusGained
        String tex;
        tex = edadTxt.getText();
        if (tex.equals("Edad")){
            edadTxt.setText("");
        }
    }//GEN-LAST:event_edadTxtFocusGained

    private void edadTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edadTxtFocusLost
        String tex;
        tex = edadTxt.getText();
        if (tex.equals("")){
            edadTxt.setText("Edad");
        }
    }//GEN-LAST:event_edadTxtFocusLost

    private void telTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telTxtFocusGained
        String tex;
        tex = telTxt.getText();
        if (tex.equals("Telefono")){
            telTxt.setText("");
        }
    }//GEN-LAST:event_telTxtFocusGained

    private void telTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telTxtFocusLost
        String tex;
        tex = telTxt.getText();
        if (tex.equals("")){
            telTxt.setText("Telefono");
        }
    }//GEN-LAST:event_telTxtFocusLost

    private void refComTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_refComTxtFocusGained
        String tex;
        tex = refComTxt.getText();
        if (tex.equals("Referencias comerciales")){
            refComTxt.setText("");
        }
    }//GEN-LAST:event_refComTxtFocusGained

    private void refComTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_refComTxtFocusLost
        String tex;
        tex = refComTxt.getText();
        if (tex.equals("")){
            refComTxt.setText("Referencias comerciales");
        }
    }//GEN-LAST:event_refComTxtFocusLost

    private void direccionTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTxtFocusGained
        String tex;
        tex = direccionTxt.getText();
        if (tex.equals("Direccion")){
            direccionTxt.setText("");
        }
    }//GEN-LAST:event_direccionTxtFocusGained

    private void direccionTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTxtFocusLost
        String tex;
        tex = direccionTxt.getText();
        if (tex.equals("")){
            direccionTxt.setText("Direccion");
        }
    }//GEN-LAST:event_direccionTxtFocusLost

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if (operacion.equals("nuevo")){
           contol.registraEmpleado(Integer.parseInt(idSucTxt.getText()), nombreTxt.getText(), Integer.parseInt(edadTxt.getText()), generoTxt.getText(), direccionTxt.getText(), telTxt.getText(), refComTxt.getText());
           idSucTxt.setText("");
           nombreTxt.setText("");
           edadTxt.setText("");
           generoTxt.setText("");
           direccionTxt.setText("");
           telTxt.setText("");
           refComTxt.setText("");
        }
        else{
            if (operacion.equals("modifica")){
                contol.corrigeEmpleado(Integer.valueOf(id),Integer.parseInt(idSucTxt.getText()), nombreTxt.getText(), Integer.parseInt(edadTxt.getText()), generoTxt.getText(), direccionTxt.getText(), telTxt.getText(), refComTxt.getText());
            }
            cargaTabla();
        }
        cargaTabla();
}//GEN-LAST:event_GuardarActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        operacion = "nuevo";
        Guardar.setEnabled(true);
        Cancelar.setEnabled(true);
        Borrar.setEnabled(true);
        Nuevo.setEnabled(false);
        idSucTxt.setEnabled(true);
        nombreTxt.setEnabled(true);
        direccionTxt.setEnabled(true);
        telTxt.setEnabled(true);
        edadTxt.setEnabled(true);
        refComTxt.setEnabled(true);
        generoTxt.setEnabled(true);
    }//GEN-LAST:event_NuevoActionPerformed

    private void tablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosMouseClicked
        int fila = tablaEmpleados.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Es necesario seleccionar un renglón");
        }
        else {
           operacion = "modifica";
           id =(String)tabla.getValueAt(fila, 0);
           idSucTxt.setText((String)tabla.getValueAt(fila, 1));
           nombreTxt.setText((String)tabla.getValueAt(fila, 2));
           edadTxt.setText((String)tabla.getValueAt(fila, 3));
           generoTxt.setText((String)tabla.getValueAt(fila, 4));
           direccionTxt.setText((String)tabla.getValueAt(fila, 5));
           telTxt.setText((String)tabla.getValueAt(fila, 6));
           refComTxt.setText((String)tabla.getValueAt(fila, 7));
           
           Guardar.setEnabled(true);
           Cancelar.setEnabled(true);
           Borrar.setEnabled(true);
           Nuevo.setEnabled(false);
           idSucTxt.setEnabled(true);
           nombreTxt.setEnabled(true);
           direccionTxt.setEnabled(true);
           telTxt.setEnabled(true);
           edadTxt.setEnabled(true);
           refComTxt.setEnabled(true);
           generoTxt.setEnabled(true);
        }
    }//GEN-LAST:event_tablaEmpleadosMouseClicked

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        if (Integer.valueOf(id)!=-1)
            contol.borraEmpleado(Integer.valueOf(id));
        cargaTabla();
    }//GEN-LAST:event_BorrarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        iniciaBotones();
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTextField buscaTxt;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JTextField edadTxt;
    private javax.swing.JTextField generoTxt;
    private javax.swing.JTextField idSucTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField refComTxt;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField telTxt;
    // End of variables declaration//GEN-END:variables
}
