/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Hitbox;
import Modelos.Mercancia;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ElErick
 */
public class Mercancias extends javax.swing.JFrame {
    DefaultTableModel tabla;
    Hitbox contol = new Hitbox ();
    String operacion = "", id = "-1";
    /**
     * Creates new form Mercancia
     */
    public Mercancias() {
        initComponents();
        setLocationRelativeTo(null);
        iniciaBotones();
        cargaTabla ();
    }
    
    public void iniciaBotones() {
        guarda.setEnabled(false);
        cancelar.setEnabled(false);
        borrar.setEnabled(false);
        nuevo.setEnabled(true);
        nombreTxt.setEnabled(false);
        descripTxt.setEnabled(false);
        precioTxt.setEnabled(false);
        sucTxt.setEnabled(false);
        canExTxt.setEnabled(false);
    }
    private void cargaTabla (){
        String [] titulos = {"Id", "Nombre", "Descripcion","Precio","Cant. Existente", "Sucursal"};
        String [] registro = new String [6];
        Mercancia mercancia;
        ArrayList mercancias;
        tabla = new DefaultTableModel(null,titulos);
        mercancias = contol.listaMercancia ();
        for (int i = 0; i<mercancias.size(); i++)
        {
            mercancia = (Mercancia) mercancias.get(i);
            registro [0] = Integer.toString (mercancia.getMercancia_id());
            registro [1] = mercancia.getNom_mercancia ();
            registro [2] = mercancia.getDescripcion ();
            registro [3] = Integer.toString (mercancia.getPrecio ());
            registro [4] = Integer.toString (mercancia.getCantidad_ext ());
            registro [5] = Integer.toString (mercancia.getSuc_codigo ());
            tabla.addRow (registro);
        }
        tablaMercancia.setModel(tabla);
        tablaMercancia.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMercancia = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        descripTxt = new javax.swing.JTextField();
        precioTxt = new javax.swing.JTextField();
        canExTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        sucTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        guarda = new javax.swing.JButton();
        buscarTxt = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();

        setTitle("Control de Mercancia");
        setResizable(false);

        tablaMercancia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripción", "Precio", "Cant. Existente", "Sucursal"
            }
        ));
        tablaMercancia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMercanciaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMercancia);

        panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        descripTxt.setText("Descripción");
        descripTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripTxtFocusLost(evt);
            }
        });
        descripTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripTxtActionPerformed(evt);
            }
        });

        precioTxt.setText("Precio");
        precioTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioTxtFocusLost(evt);
            }
        });
        precioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTxtActionPerformed(evt);
            }
        });

        canExTxt.setText("Cantidad existente");
        canExTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                canExTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                canExTxtFocusLost(evt);
            }
        });
        canExTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canExTxtActionPerformed(evt);
            }
        });

        nombreTxt.setText("Nombre");
        nombreTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTxtFocusLost(evt);
            }
        });
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });

        sucTxt.setText("N° de sucursal");
        sucTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sucTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sucTxtFocusLost(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/descripción.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/money.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/icon2.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/caja.png"))); // NOI18N

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/Nuevo_icono_restricción_prohibida.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/icono-aniadir.gif"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/icono_borrar_objeto.gif"))); // NOI18N
        borrar.setText("Borrar");
        borrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        guarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/disquete.gif"))); // NOI18N
        guarda.setText("Guardar");
        guarda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                            .addComponent(descripTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sucTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(canExTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guarda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descripTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(precioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(canExTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sucTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(guarda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        buscarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTxtActionPerformed(evt);
            }
        });

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Pictures/icono_buscar.gif"))); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripTxtActionPerformed

    private void precioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTxtActionPerformed

    private void canExTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canExTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canExTxtActionPerformed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void buscarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarTxtActionPerformed

    private void nombreTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTxtFocusGained
        String tex;
        tex = nombreTxt.getText();
        if (tex.equals("Nombre")){
            nombreTxt.setText("");
        }
    }//GEN-LAST:event_nombreTxtFocusGained

    private void nombreTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTxtFocusLost
        String tex;
        tex = nombreTxt.getText();
        if (tex.equals("")){
            nombreTxt.setText("Nombre");
        }
    }//GEN-LAST:event_nombreTxtFocusLost

    private void descripTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripTxtFocusGained
        String tex;
        tex = descripTxt.getText();
        if (tex.equals("Descripción")){
            descripTxt.setText("");
        }
    }//GEN-LAST:event_descripTxtFocusGained

    private void descripTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripTxtFocusLost
        String tex;
        tex = descripTxt.getText();
        if (tex.equals("")){
            descripTxt.setText("Descripción");
        }
    }//GEN-LAST:event_descripTxtFocusLost

    private void precioTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioTxtFocusGained
        String tex;
        tex = precioTxt.getText();
        if (tex.equals("Precio")){
            precioTxt.setText("");
        }
    }//GEN-LAST:event_precioTxtFocusGained

    private void precioTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioTxtFocusLost
        String tex;
        tex = precioTxt.getText();
        if (tex.equals("")){
            precioTxt.setText("Precio");
        }
    }//GEN-LAST:event_precioTxtFocusLost

    private void canExTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_canExTxtFocusGained
        String tex;
        tex = canExTxt.getText();
        if (tex.equals("Cantidad existente")){
            canExTxt.setText("");
        }
    }//GEN-LAST:event_canExTxtFocusGained

    private void canExTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_canExTxtFocusLost
        String tex;
        tex = canExTxt.getText();
        if (tex.equals("")){
            canExTxt.setText("Cantidad existente");
        }
    }//GEN-LAST:event_canExTxtFocusLost

    private void sucTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sucTxtFocusGained
        String tex;
        tex = sucTxt.getText();
        if (tex.equals("N° de sucursal")){
            sucTxt.setText("");
        }
    }//GEN-LAST:event_sucTxtFocusGained

    private void sucTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sucTxtFocusLost
        String tex;
        tex = sucTxt.getText();
        if (tex.equals("")){
            sucTxt.setText("N° de sucursal");
        }
    }//GEN-LAST:event_sucTxtFocusLost

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        iniciaBotones();
}//GEN-LAST:event_cancelarActionPerformed

    private void guardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardaActionPerformed
        if (operacion.equals("nuevo")){
           contol.registraMercancia(nombreTxt.getText(), descripTxt.getText(), Integer.parseInt(precioTxt.getText()), Integer.parseInt(canExTxt.getText()),Integer.parseInt(sucTxt.getText()));
           nombreTxt.setText("");
           descripTxt.setText("");
           precioTxt.setText("");
           sucTxt.setText("");
           canExTxt.setText("");
        }
        else{
            if (operacion.equals("modifica")){
                contol.corrigeSucursal(Integer.valueOf(id),nombreTxt.getText(), descripTxt.getText(), Integer.parseInt(precioTxt.getText()), Integer.parseInt(canExTxt.getText()),Integer.parseInt(sucTxt.getText()));
            }
            cargaTabla();
        }
        cargaTabla();
}//GEN-LAST:event_guardaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String [] titulos = {"Id", "Nombre", "Descripcion","Precio","Cant. Existente", "Sucursal"};
        String [] registro = new String [5];
        Mercancia mercancia;
        ArrayList mercancias;
        tabla = new DefaultTableModel(null,titulos);
        mercancias = contol.listaMercanciaBuscados (buscarTxt.getText());
        for (int i = 0; i<mercancias.size(); i++)
        {
            mercancia = (Mercancia) mercancias.get(i);
            registro [0] = Integer.toString (mercancia.getMercancia_id());
            registro [1] = mercancia.getNom_mercancia ();
            registro [2] = mercancia.getDescripcion ();
            registro [3] = Integer.toString (mercancia.getPrecio ());
            registro [4] = Integer.toString (mercancia.getCantidad_ext ());
            registro [5] = Integer.toString (mercancia.getSuc_codigo ());
            tabla.addRow (registro);
        }
        tablaMercancia.setModel(tabla);
        tablaMercancia.setEnabled(true);
    }//GEN-LAST:event_buscarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        operacion = "nuevo";
        guarda.setEnabled(true);
        cancelar.setEnabled(true);
        borrar.setEnabled(true);
        nuevo.setEnabled(false);
        nombreTxt.setEnabled(true);
        descripTxt.setEnabled(true);
        precioTxt.setEnabled(true);
        sucTxt.setEnabled(true);
        canExTxt.setEnabled(true);
    }//GEN-LAST:event_nuevoActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        if (Integer.valueOf(id)!=-1)
            contol.borraMercancia(Integer.valueOf(id));
        cargaTabla();
    }//GEN-LAST:event_borrarActionPerformed

    private void tablaMercanciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMercanciaMouseClicked
        int fila = tablaMercancia.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Es necesario seleccionar un renglón");
        }
        else {
           operacion = "modifica";
           id =(String)tabla.getValueAt(fila, 0);
           nombreTxt.setText((String)tabla.getValueAt(fila, 1));
           descripTxt.setText((String)tabla.getValueAt(fila, 2));
           precioTxt.setText((String)tabla.getValueAt(fila, 3));
           canExTxt.setText((String)tabla.getValueAt(fila, 4));
           sucTxt.setText((String)tabla.getValueAt(fila, 5));
           guarda.setEnabled(true);
           cancelar.setEnabled(true);
           borrar.setEnabled(true);
           nuevo.setEnabled(false);
           nombreTxt.setEnabled(true);
           descripTxt.setEnabled(true);
           precioTxt.setEnabled(true);
           sucTxt.setEnabled(true);
           canExTxt.setEnabled(true);
        }
    }//GEN-LAST:event_tablaMercanciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mercancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mercancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mercancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mercancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mercancias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JTextField canExTxt;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField descripTxt;
    private javax.swing.JButton guarda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JButton nuevo;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JTextField sucTxt;
    private javax.swing.JTable tablaMercancia;
    // End of variables declaration//GEN-END:variables
}
